import {
  SignIn,
  SignInButton,
  SignOutButton,
  SignUp,
  UserButton,
  useUser,
} from "@clerk/nextjs";
import Head from "next/head";
import Link from "next/link";
import { Button } from "~/components/ui/button";
import { api } from "~/utils/api";

export default function Home() {
  const { data } = api.leave.getAll.useQuery();
  console.log(data);
  const user = useUser();

  return (
    <>
      <Head>
        <title>Leave Application</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Leave Application
          </h1>
          <div>{!user.isSignedIn && <SignInButton />}</div>
          <SignIn path="/sign-in" routing="path" signUpUrl="/sign-up" />
          <div> {user.isSignedIn && <UserButton afterSignOutUrl="/" />}</div>
          <p className="text-2xl text-white">
            {user.isSignedIn ? user.user.fullName : "Signing in..."}
          </p>
          <div>
            {data?.map((leave) => (
              <div>
                <div>
                  {leave.name} : {leave.reason}
                </div>
                <div>
                  <Button>Delete</Button>
                </div>
              </div>
            ))}
          </div>
        </div>
      </main>
    </>
  );
}
